name: C++ Unit Test

on:
  push:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp/**'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S cpp -B cpp/build

    - name: Build
      run: cmake --build cpp/build

    - name: Test
      working-directory: ./cpp/build
      run: ctest --output-on-failure
