name: Dart Unit Test

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'dart/**'
  #     - '.github/workflows/dart/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'dart/**'
  #     - '.github/workflows/dart/**'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1

    - name: Install dependencies
      working-directory: ./dart
      run: dart pub get

    - name: Run tests
      working-directory: ./dart
      run: dart test
