name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  python-test:
    uses: ./.github/workflows/python-test.yml

  rust-test:
    uses: ./.github/workflows/rust-test.yml
  
  go-test:
    uses: ./.github/workflows/go-test.yml

  java-test:
    uses: ./.github/workflows/java-test.yml

  csharp-test:
    uses: ./.github/workflows/csharp-test.yml

  js-ts-test:
    uses: ./.github/workflows/js-ts-test.yml

  kotlin-test:
    permissions:
      contents: read
    uses: ./.github/workflows/kotlin-test.yml
