name: Python Unit Test

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     # - 'python/**'
  #     - '.github/workflows/python/python-test.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     # - 'python/**'
  #     - '.github/workflows/python/python-test.yml'
  workflow_call:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        working-directory: ./python
        run: |
          pip install -e .[test]

      - name: Install pytest
        working-directory: ./python
        run: python -m pip install pytest

      - name: Run Python tests
        working-directory: ./python
        run: |
          pytest
