name: Swift Unit Test

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'swift/**'
  #     - '.github/workflows/swift/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'swift/**'
  #     - '.github/workflows/swift/**'
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./swift
      run: swift build
    - name: Run tests
      working-directory: ./swift
      run: swift test
